n_rows = 500
n_cols = 500
radius = 4
pop_dens = 1.0
n_cycles = 50
R_0 = 1.5
time_contagious = 10
case_fat_risk = 0.1
t_I = 8
p_R = 0.9
t_F = 0
t_L = 0
t_R = 15
p_S = 0.9
t_S = 0
E_in = 100
I_in = 200