n_rows = 400
n_cols = 400
radius = 3
pop_dens = 0.96
n_cycles = 700
R_0 = 3.0
time_contagious = 10
case_fat_risk = 0.1
t_I = 8
p_R = 0.9
t_F = 15
t_L = 0
t_R = 15
p_S = 0.9
t_S = 0
E_in = 200
I_in = 10
p_displ = 0.5
max_people = 4
p_e = 0.0