n_rows = 11
n_cols = 7
radius = 6
pop_dens = 0.99
n_cycles = 30
R_0 = 10.0
time_contagious = 10
case_fat_risk = 1.0
t_I = 0
p_R = 0.0
t_F = 0
t_L = 0
t_R = 1
p_S = 0.0
t_S = 0
E_in = 3
I_in = 1